services:
    odiseo_sylius_amazon_fba_plugin.command.update_stock:
        class: Odiseo\SyliusAmazonFBAPlugin\Command\UpdateAmazonFBAStockCommand
        arguments:
            - '@odiseo_sylius_amazon_fba_plugin.api.amazon_fba_manager'
            - '@sylius.manager.product_variant'
            - '@sylius.repository.product_variant'
        tags:
            - { name: console.command, command: 'odiseo:amazon-fba:update-stock' }
