# This file is part of the Odiseo Amazon FBA Plugin package, a commercial software.
# Only users who have purchased a valid license and accept to the terms of the License Agreement can install
# and use this program.
# Copyright (c) 2018-2024 - Pablo D'amico

services:
    odiseo_sylius_amazon_fba_plugin.form.type.amazon_fba_configuration:
        class: Odiseo\SyliusAmazonFBAPlugin\Form\Type\AmazonFBAConfigurationType
        arguments:
            - '%odiseo_sylius_amazon_fba_plugin.model.amazon_fba_configuration.class%'
            - ['odiseo']
        tags:
            - { name: form.type, alias: odiseo_sylius_amazon_fba_configuration }
