odiseo_sylius_amazon_fba_plugin_admin_amazon_fba_configuration:
    resource: |
        alias: odiseo_sylius_amazon_fba_plugin.amazon_fba_configuration
        section: admin
        templates: "@SyliusAdmin/Crud"
        except: ['show']
        redirect: index
        grid: odiseo_sylius_amazon_fba_plugin_amazon_fba_configuration
        permission: true
        vars:
            all:
                subheader: odiseo_sylius_amazon_fba_plugin.ui.manage_configurations
                templates:
                    form: '@OdiseoSyliusAmazonFBAPlugin/Admin/AmazonFBAConfiguration/_form.html.twig'
            index:
                icon: cog
    type: sylius.resource
